version: 2

models:
  - name: fct_customer_behavior
    description: Aggregated metrics for customer behavior including spend, feedback, and support
    columns:
      - name: customer_id
        tests:
          - not_null
          - unique
      - name: total_spent
        tests:
          - dbt_utils.accepted_range:
              min_value: 0
      - name: avg_feedback_rating
        tests:
          - dbt_utils.accepted_range:
              min_value: 1
              max_value: 5
      - name: support_ticket_count
        tests:
          - dbt_utils.accepted_range:
              min_value: 0
              max_value: 100
